version: 2
before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./internal/static/
builds:
  - id: markview-darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/kooksee/markview/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: markview-windows
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/kooksee/markview/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
  - id: markview-linux
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/kooksee/markview/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - id: markview-archive
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if
      .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: darwin
        formats:
          - zip
    files:
      - LICENSE
      - docs/CREDITS
      - README.md
      - CHANGELOG.md
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - id: markview-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    ids:
      - markview-linux
    homepage: https://github.com/kooksee/markview
    maintainer: barry <kooksee@163.com>
    description: "markview is a Markdown viewer that opens .md files in a browser"
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: "1"
release:
  use_existing_draft: true
